import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import { getServerSession } from 'next-auth'
import Login from '@/components/Login';
import Authprovider from '../components/Authprovider'
import ClientProvider from '@/components/ClientProvider'
// import { authOptions } from './api/auth/[...nextauth]/route'
// import {authOptions} from '../app/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'gpt clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session=await getServerSession();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Authprovider session={session}>
          {!session?(
            <Login></Login>
          ):(
            <div className='flex'>
            <div className='bg-[#202123]'>
            <Sidebar/>
            </div>
            <ClientProvider/>
            
          <div className='bg-[#343541] flex-1'>{children}</div>
          </div>
          )}
       
        </Authprovider>
      
        </body>
        
    </html>
  )
}
